apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: 2 # Reduced for Minikube environment
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: chat-app:latest
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: chat-app-secrets
                key: MONGO_URI
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: chat-app-secrets
                key: OPENAI_API_KEY
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"   # Reduced for Minikube
            cpu: "100m"
          limits:
            memory: "128Mi"  # Reduced for Minikube
            cpu: "200m"
