apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: 1 # Reduced for Minikube environment
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: chat-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_URI
            value: "mongodb://mongodb:27017/chat_app"
        resources:
          requests:
            memory: "64Mi"   # Reduced for Minikube
            cpu: "100m"
          limits:
            memory: "128Mi"  # Reduced for Minikube
            cpu: "200m"
