name: Flask App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-cov

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

    - name: Test with pytest
      env:
        APP_HOST: ${{ secrets.APP_HOST }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python -m pytest --cov=./ --cov-report=term-missing

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    services:
      mongodb:
        image: mongo:8
        ports:
          - 27017:27017

  build:
    needs: lint-and-test
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Run Docker Compose and Test App
      env:
        APP_HOST: ${{ secrets.APP_HOST }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        docker compose up -d
        sleep 5
        curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:5000/

